---
- name: Add af_key mod
  tags: docker-run
  modprobe:
    name: af_key
    state: present

- name: docker pull hwdsl2/ipsec-vpn-server
  tags: docker-run
  docker_image:
    name: hwdsl2/ipsec-vpn-server

- name: Copy
  tags: copy
  copy:
    src: files/docker-build.sh
    dest: "/home/ubuntu/docker-build.sh"

- name: Copy
  tags: copy
  copy:
    src: files/vpn-env.ini
    dest: "/home/ubuntu/vpn-env.ini"

- name: Build and run application
  tags: docker-run
  become: true
  docker_container:
    name: ipsec-vpn-server
    image: hwdsl2/ipsec-vpn-server
    state: started
    restart: yes
    privileged: true
    ports:
    - "500:500/udp"
    - "4500:4500/udp"
    env:
      VPN_USER: 'vpnuser'
      VPN_PASSWORD: 'vpnpassword'
      VPN_IPSEC_PSK: 'ipsec'
    volumes:
    - "/lib/modules:/lib/modules:ro"
